version: '3'
services:
  gateway-duckduckgo-sse:
    image: docker/mcp-gateway
    command:
      - --port=8081
      - --transport=sse
      - --verbose
      - --servers=duckduckgo
    ports:
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  gateway-duckduckgo-streaming:
    image: docker/mcp-gateway
    command:
      - --port=8083
      - --transport=streaming
      - --verbose
      - --servers=duckduckgo
    ports:
      - "8083:8083"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock