name: JAICF CI for Github

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGO_URL: mongodb://localhost:27017

    steps:
      - uses: actions/checkout@v2

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-port: 27017

      - name: Set up JDK 9
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Grant execute permission for gradle
        run: |
          chmod +x gradlew
          chmod +x gradle/wrapper/gradle-wrapper.jar

      - name: Build with Gradle
        run: ./gradlew build
